TrainingArguments:
  output_dir: checkpoint
  evaluation_strategy: epoch
  learning_rate: 2e-5
  num_train_epochs: 60
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 32
  warmup_steps: 500
  weight_decay: 0.01
  save_total_limit: 2
  gradient_accumulation_steps: 4
  logging_dir: artifacts/model_trainer
  save_strategy: epoch
  load_best_model_at_end: true
  metric_for_best_model: eval_loss
  greater_is_better: false
  fp16: true
