artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: samsum
  local_data_file: artifacts/data_ingestion/samsum

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILLS: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum
  tokenizer_name: google-t5/t5-small


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/samsum
  model_ckpt: google-t5/t5-small


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum
  model_path: artifacts/model_trainer/t5-small-samsum
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv